# Generated by Django 5.0.6 on 2025-10-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_applied_voucher_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='seller_reply_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
