# Generated by Django 4.2.16 on 2025-10-24 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('discount_type', models.CharField(choices=[('PERCENT', 'PERCENT'), ('AMOUNT', 'AMOUNT')], default='PERCENT', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='api.seller')),
            ],
            options={
                'unique_together': {('seller', 'code')},
            },
        ),
    ]
