# Generated by Django 4.2.16 on 2025-10-24 18:02

from django.db import migrations, models
import django.utils.timezone
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_notes_order_payment_status_order_shipping_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(default='VND', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='inventory_type',
            field=models.CharField(choices=[('FINITE', 'FINITE'), ('BACKORDER', 'BACKORDER')], default='FINITE', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_class',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, null=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('PUBLISHED', 'PUBLISHED')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='payout_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='seller',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='seller',
            name='slug',
            field=models.SlugField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='seller',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('SUSPENDED', 'SUSPENDED')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='voucher',
            name='applicable_product_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='voucher',
            name='min_order_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='voucher',
            name='per_user_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='usage_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('AWAITING_INFO', 'AWAITING_INFO')], default='PENDING', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('seller', 'sku'), ('seller', 'slug')},
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SALE', 'SALE'), ('REFUND', 'REFUND'), ('FEE', 'FEE'), ('PAYOUT', 'PAYOUT')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='VND', max_length=10)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.seller')),
            ],
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bank_account', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to='api.seller')),
            ],
        ),
    ]
