# Generated by Django 4.2.16 on 2025-10-24 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_category_product_currency_product_dimensions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='collected_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='events',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='evidence_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='picked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipper',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shipper',
            name='bank_account',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='shipper',
            name='license_image',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='shipper',
            name='service_areas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='shipper',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('SUSPENDED', 'SUSPENDED')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'ASSIGNED'), ('ACCEPTED', 'ACCEPTED'), ('PICKED', 'PICKED'), ('ENROUTE', 'ENROUTE'), ('IN_TRANSIT', 'IN_TRANSIT'), ('ARRIVED', 'ARRIVED'), ('DELIVERED', 'DELIVERED'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='ASSIGNED', max_length=20),
        ),
        migrations.CreateModel(
            name='ShippingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('location', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_events', to='api.deliverytask')),
            ],
        ),
        migrations.CreateModel(
            name='ShipperLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('ts', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='api.shipper')),
            ],
        ),
    ]
